### ISSUE TITLE
Convert wiki to simple markdown files

### ISSUE THREAD

**Issue by ilyaglow** [GrrrDog/weird_proxies#1]
Hey, 

Firstly, thank you for your work and open sourcing it!

Did you consider to use simple markdown files for the content in the repo?

It would be much easier for others to watch for new changes, contribute to your repository and improve it.

**Comment by GrrrDog** [comment]
Hi,
Actually, you can access a wiki as a repo with markdown files. But, probably, you are right, it's more convenient. Moreover, one good person, @denji,  has transformed and push it.
